In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [6]:
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [7]:
slice3=arr[::3]
print(slice3)

[1 4 7]


In [8]:
import numpy as np
x=([1,2,3,4,5,6,7,8,9])
reversed_x=x[::-1]
print(reversed_x)

[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [11]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=a[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [14]:
print(a[:2,:1])

[[1]
 [4]]


In [16]:
col1=a[:,0]
print(col1)

[1 4 7]


In [17]:
r1=a[0,:]
print(r1)

[1 2 3]


In [18]:
print(a[0:2:1])

[[1 2 3]
 [4 5 6]]


In [20]:
print(a[0:1:2])

[[1 2 3]]


In [22]:
import numpy as np
import array
arr=array.array('i',[10,20,30,40,50])
print(arr[0])
print(arr[3])

10
40


In [23]:
#for multidimensional array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[2,1])

1
8


In [24]:
#positive indexing
arr=[10,20,30]
print("positive indexing:",arr[1])

positive indexing: 20


In [25]:
a=[10,30,20,40]
print("negative indexing:",arr[-2])

negative indexing: 20


In [27]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [30]:
print(arr[[1,3]])

[20 40]


In [1]:
#numpy horizontal join
import numpy as np
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
result=np.hstack((a1,a2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [3]:
#vertical join
import numpy as np
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
result=np.vstack((a1,a2))
print("vertical join:\n",result)

vertical join:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
#depth join
result=np.dstack((a1,a2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [7]:
#array splitting
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,2)
print(result)

[array([1, 2, 3]), array([4, 5, 6])]


In [8]:
result=np.array_split(arr,4)
print(result)

[array([1, 2]), array([3, 4]), array([5]), array([6])]
