In [1]:
import numpy as np
a=np.array([10,20,30,40])
print("one dimensional array:",a)

one dimensional array: [10 20 30 40]


In [2]:
import numpy as np 
a=np.array(([1,2,3],[4,5,6]))
print("two dimensional array:",a)

two dimensional array: [[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
a=np.array((([1,2,3],[4,5,6],[7,8,9])))
print("three dimensional array:",a)

three dimensional array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
c=np.zeros((3,5))
print("/n array with all zeros:\n",c)

/n array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
import numpy as np
d=np.random.random((3,5))
print("\n random value :\n",d)


 random value :
 [[0.09441939 0.75002724 0.58220348 0.15385529 0.37687797]
 [0.4039017  0.91708091 0.22741049 0.25797192 0.04890346]
 [0.84300356 0.85932937 0.07108792 0.91499752 0.8586549 ]]


In [9]:
import numpy as np
e=np.arange(0,10,1)
print("\n sequence value:\n",e)


 sequence value:
 [0 1 2 3 4 5 6 7 8 9]


In [13]:
import numpy as np
orgarr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=orgarr.reshape(4,3)
print(" \n orginal array:\n",orgarr)
print("\n reshaped array:\n",newarr)

 
 orginal array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8])
slice=arr[2:6]
print(slice)

[3 4 5 6]


In [13]:
slice1=arr[::2]
print(slice1)

[1 3 5 7]


In [15]:
import numpy as np
arr=([1,2,3,4,5,6,7,8])
reversed_arr=arr[::-1]
print(reversed_arr)

[8, 7, 6, 5, 4, 3, 2, 1]


In [17]:
slice2=arr[::3]
print(slice2)

[1, 4, 7]


In [19]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9,]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [21]:
col1=arr[:,0]
print(col1)

[1 4 7]


In [30]:
row1=arr[0,:]
print(row1)

[1 2 3]


In [44]:
print(arr[0:2:1])

[[1 2 3]
 [4 5 6]]


In [50]:
import numpy as np
import array
arr=array.array('i',[10,20,30,40,50])
print(arr[0])
print(arr[3])

10
40


In [52]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[2,1])

1
8


In [54]:
import numpy as np
arr=([10,20,30])
print(arr[1])

20


In [56]:
import numpy as np
print(arr[-1])

30


In [1]:
import numpy aa np
arr=np.

SyntaxError: invalid syntax (4047339840.py, line 1)