In [1]:
import numpy as np
m=np.random.random((3,4))
print("Random values:\n",m)

Random values:
 [[0.86464771 0.18690965 0.9423038  0.26459988]
 [0.56790097 0.31398673 0.22686707 0.58548506]
 [0.36865043 0.36110047 0.49238855 0.141885  ]]


In [2]:
import numpy as np
x=np.zeros((3,4))
print("Array with all Zeros:\n",x)

Array with all Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
import numpy as np
y=np.arange(5,30,2)
print("Sequenced Array:",y)

Sequenced Array: [ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [5]:
import numpy as np
a=np.array([[1,7,2,4],[0,9,3,6]])
print("Shape of the array:",a.shape)
print("No.Of.Dimensions:",a.ndim)
print("Datatype of the array:",a.dtype)

Shape of the array: (2, 4)
No.Of.Dimensions: 2
Datatype of the array: int64


In [6]:
b=a.flatten()
print("Original Array:\n",a)
print("Flattened Array:\n",b)

Original Array:
 [[1 7 2 4]
 [0 9 3 6]]
Flattened Array:
 [1 7 2 4 0 9 3 6]
